name: NoItemAbuse
main: noitemabuse.NoItemAbuse
version: POMVersion
description: Prevents illegitimate items from being used
author: Ruan
website: https://github.com/ruany/NoItemAbuse
commands:
  noitemabuse:
    aliases: [nia]
    usage: /<command> toggle